### ISSUE TITLE
Unable to load element js when deployed using aurelia-cli

### ISSUE THREAD

**Issue by hozn** [aurelia-plugins/aurelia-plugins-google-recaptcha#7]
We're building with Aurelia CLI and it works great locally (`au run --watch`) but when we bundle our vendor js and deploy, I see an error trying to load element js.

Installed per instructions, using npm.  Version:
```
➜  selfcare-login git:(master) ✗ cat package.json| grep recaptcha
    "aurelia-plugins-google-recaptcha": "^2.5.2",
```

And `aurelia.json` looks like:
```json
{
  "name": "aurelia-plugins-google-recaptcha",
  "path": "../node_modules/aurelia-plugins-google-recaptcha/dist/amd",
  "main": "aurelia-plugins-google-recaptcha"
}
```

Also updated the prepend section, mine looks like:
```json
"prepend": [
          "node_modules/jquery/dist/jquery.js",
          "node_modules/babel-polyfill/dist/polyfill.min.js",
          "node_modules/bootstrap/dist/js/bootstrap.min.js",
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "node_modules/whatwg-fetch/fetch.js",
          "node_modules/requirejs/require.js"
        ],
```

But when I try to load my deployed application (nginx in Docker), I see in the logs:
```
2017/09/25 19:40:48 [error] 5#5: *4 open() "/usr/share/nginx/html/login/node_modules/aurelia-plugins-google-recaptcha/dist/amd/aurelia-plugins-google-recaptcha-element.js" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /login/node_modules/aurelia-plugins-google-recaptcha/dist/amd/aurelia-plugins-google-recaptcha-element.js HTTP/1.1", host: "localhost:8011", referrer: "http://localhost:8011/login/"
```

I'm sure there's something dumb I've forgotten to do, but at this point feel like I've done the due diligence to read the docs, etc. 

Thanks for any help!

**Update:**
- I also tried upgrading to `aurelia-cli@0.25.0`
- And then using:
```
au import aurelia-plugins-google-recaptcha
```

But it appears to only have made superficial modifications to my `aurelia.json` file and the error remains the same.

**Comment by bartlenaerts** [comment]
Latest version of the plugin (v2.6.1) works perfectly with latest version of aurelia-cli (0.33.1).
